"""empty message

Revision ID: 1bf27fdb5f2a
Revises: 3bd2ff16f3e7
Create Date: 2019-10-01 08:40:07.568374

"""

# revision identifiers, used by Alembic.
revision = '1bf27fdb5f2a'
down_revision = '3bd2ff16f3e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
